name    'ghoneycutt-generic'
version '1.0.1'

# included on PuppetForge are ghoneycutt-centos and
# ghoneycutt-redhat, since these are my primary values
# for $operatingsystem
#dependency 'ghoneycutt-$operatingsystem', '>= 1.0.0'
dependency 'ghoneycutt/backup', '>= 1.0.0'
dependency 'ghoneycutt/certs', '>= 1.0.0'
dependency 'ghoneycutt/dnsclient', '>= 1.0.0'
dependency 'ghoneycutt/facter', '>= 1.0.0'
dependency 'ghoneycutt/hosts', '>= 1.0.0'
dependency 'ghoneycutt/logrotate', '>= 1.0.0'
dependency 'ghoneycutt/logwatch', '>= 1.0.0'
dependency 'ghoneycutt/postfix', '>= 1.0.0'
dependency 'ghoneycutt/puppet', '>= 1.0.0'
dependency 'ghoneycutt/rsync', '>= 1.0.0'
dependency 'ghoneycutt/snmp', '>= 1.0.0'
dependency 'ghoneycutt/ssh', '>= 1.0.0'
dependency 'ghoneycutt/sudo', '>= 1.0.0'
dependency 'ghoneycutt/syslog_ng', '>= 1.0.0'
dependency 'ghoneycutt/utils', '>= 1.0.0'
dependency 'ghoneycutt/vim', '>= 1.0.0'
